set(_CATKIN_CURRENT_PACKAGE "pleora_polarcam")
set(pleora_polarcam_VERSION "1.0.0")
set(pleora_polarcam_MAINTAINER "Alberto Invernizzi <alby.inve@gmail.com>")
set(pleora_polarcam_PACKAGE_FORMAT "1")
set(pleora_polarcam_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "dynamic_reconfigure" "camera_info_manager" "driver_base" "curl" "gnutls")
set(pleora_polarcam_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "dynamic_reconfigure" "camera_info_manager" "curl" "gnutls")
set(pleora_polarcam_BUILDTOOL_DEPENDS "catkin")
set(pleora_polarcam_BUILDTOOL_EXPORT_DEPENDS )
set(pleora_polarcam_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "dynamic_reconfigure" "camera_info_manager" "curl" "gnutls")
set(pleora_polarcam_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "dynamic_reconfigure" "camera_info_manager" "curl" "gnutls")
set(pleora_polarcam_TEST_DEPENDS )
set(pleora_polarcam_DOC_DEPENDS )
set(pleora_polarcam_DEPRECATED "")